import operator
from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length
    # Brief per-round referee verdict appended to history so debaters can see
    # which of their points were scored as conceded/unsupported.
    referee_notes: Annotated[str, "Running referee verdicts across rounds"]


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length
    # Running per-round referee verdicts for the risk debate, so debaters can
    # see which of their points were scored as conceded/unsupported.
    referee_notes: Annotated[str, "Running risk-debate referee verdicts across rounds"]


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    macro_report: Annotated[str, "Report from the Macro Analyst"]
    business_report: Annotated[str, "Report from the Business Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # Canonical, reconciled facts block shared by every downstream agent so
    # the debate argues from one set of numbers instead of each agent
    # re-fetching slightly different ones (e.g. price drift across sections).
    facts_snapshot: Annotated[str, "Canonical facts block compiled once after the analysts finish"]
    # Output of the post-debate fact-check: a markdown list of claims made in
    # the debate that are unsupported or contradicted by the source reports.
    claim_audit: Annotated[str, "Flagged unsupported/contradicted debate claims for the decision agents"]
    # Set True by the mid-debate referee once both sides are only restating
    # themselves, allowing the debate to end before the round cap.
    debate_converged: Annotated[bool, "Whether the bull/bear debate has converged"]
    # Set True by the risk-debate referee once all three risk analysts are
    # only restating themselves, allowing the risk debate to end before the
    # round cap instead of running fixed restating rounds.
    risk_debate_converged: Annotated[bool, "Whether the risk debate has converged"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # Accumulated tool errors across all analyst runs — drained from the
    # ToolErrorCollector after the graph finishes so they persist in the
    # state log for post-run debugging.
    tool_errors: Annotated[list[dict], operator.add] = []
